import os
import re
from io import BytesIO

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt
from fpdf import FPDF

from backend.utils.text import sanitize_text


PROJECT_ROOT = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)

LOGO_PATH = os.path.join(
    PROJECT_ROOT,
    "backend",
    "assets",
    "logo.png",
)


def clean_text(text):
    if text is None:
        return ""

    text = sanitize_text(str(text))

    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u2022": "-",
        "\u00a0": " ",
        "\t": "    ",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text


# ============================================================
# TXT
# ============================================================

def make_txt(text, document_type="Legal Document"):
    text = clean_text(text)

    header = (
        f"{document_type}\n"
        f"{'=' * len(document_type)}\n\n"
    )

    footer = (
        "\n\n"
        "Generated by LegalEase\n"
        "AI-assisted legal draft. Review before signing or relying on this document.\n"
    )

    return (header + text + footer).encode("utf-8")


# ============================================================
# DOCX
# ============================================================

def make_docx(text, document_type="Legal Document"):
    text = clean_text(text)

    document = Document()

    section = document.sections[0]
    section.top_margin = Inches(0.8)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)

    # Logo
    if os.path.isfile(LOGO_PATH):
        logo_paragraph = document.add_paragraph()
        logo_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

        run = logo_paragraph.add_run()
        run.add_picture(
            LOGO_PATH,
            width=Inches(1.1)
        )

    # Title
    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = title.add_run(document_type)
    run.bold = True
    run.font.name = "Times New Roman"
    run.font.size = Pt(18)

    document.add_paragraph()

    # Body
    for line in text.splitlines():

        line = line.strip()

        if not line:
            document.add_paragraph()
            continue

        paragraph = document.add_paragraph()

        if re.match(r"^\d+[\.\)]\s+", line):
            run = paragraph.add_run(line)
            run.bold = True

        elif line.upper() == line and len(line) < 100:
            run = paragraph.add_run(line)
            run.bold = True

        else:
            run = paragraph.add_run(line)

        run.font.name = "Times New Roman"
        run.font.size = Pt(11)

        paragraph.paragraph_format.space_after = Pt(5)
        paragraph.paragraph_format.line_spacing = 1.15

    # Footer
    footer = section.footer
    footer_paragraph = footer.paragraphs[0]
    footer_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

    footer_run = footer_paragraph.add_run(
        "LegalEase - AI-assisted legal draft"
    )

    footer_run.font.name = "Times New Roman"
    footer_run.font.size = Pt(9)

    output = BytesIO()
    document.save(output)

    return output.getvalue()


# ============================================================
# PDF
# ============================================================

class LegalPDF(FPDF):

    def __init__(
        self,
        brand_name="LegalEase",
        document_type="Legal Document",
    ):
        super().__init__()

        self.brand_name = brand_name
        self.document_type = document_type

        self.set_auto_page_break(
            auto=True,
            margin=20
        )

        self.set_margins(
            left=18,
            top=30,
            right=18
        )

        self.add_page()

    def header(self):

        # Logo
        if os.path.isfile(LOGO_PATH):
            try:
                self.image(
                    LOGO_PATH,
                    x=88,
                    y=8,
                    w=34
                )
            except Exception:
                pass

        # Document title
        self.set_y(32)

        self.set_font(
            "Times",
            "B",
            14
        )

        self.cell(
            0,
            7,
            self.document_type,
            align="C"
        )

        self.ln(16)

    def footer(self):

        self.set_y(-15)

        self.set_font(
            "Times",
            "",
            8
        )

        self.cell(
            0,
            5,
            f"{self.brand_name} - AI-assisted legal draft",
            align="C"
        )


# ============================================================
# SAFE MANUAL TEXT WRAPPING
# IMPORTANT: NO multi_cell() IS USED
# ============================================================

def _pdf_wrap_text(pdf, text, max_width):

    text = clean_text(text)

    if not text:
        return [""]

    words = text.split()

    lines = []
    current = ""

    for word in words:

        # Handle very long words
        if pdf.get_string_width(word) > max_width:

            if current:
                lines.append(current)
                current = ""

            piece = ""

            for char in word:

                test = piece + char

                if pdf.get_string_width(test) <= max_width:
                    piece = test

                else:
                    if piece:
                        lines.append(piece)

                    piece = char

            if piece:
                current = piece

            continue

        test = word if not current else current + " " + word

        if pdf.get_string_width(test) <= max_width:
            current = test

        else:
            if current:
                lines.append(current)

            current = word

    if current:
        lines.append(current)

    return lines or [""]


def _pdf_write_wrapped(pdf, text):

    text = clean_text(text)

    page_width = (
        pdf.w
        - pdf.l_margin
        - pdf.r_margin
    )

    line_height = 6

    lines = _pdf_wrap_text(
        pdf,
        text,
        page_width
    )

    for line in lines:

        if pdf.get_y() > pdf.h - 25:
            pdf.add_page()

        pdf.text(
            pdf.l_margin,
            pdf.get_y() + 4.5,
            line
        )

        pdf.ln(line_height)


# ============================================================
# PDF EXPORT
# ============================================================

def make_pdf(text, document_type="Legal Document"):

    text = clean_text(text)

    pdf = LegalPDF(
        brand_name="LegalEase",
        document_type=document_type
    )

    pdf.set_font(
        "Times",
        "",
        11
    )

    for raw_line in text.splitlines():

        line = raw_line.strip()

        # Empty line
        if not line:
            pdf.ln(4)
            continue

        # Numbered heading
        if re.match(r"^\d+[\.\)]\s+", line):

            if pdf.get_y() > pdf.h - 30:
                pdf.add_page()

            pdf.set_font(
                "Times",
                "B",
                11
            )

            _pdf_write_wrapped(
                pdf,
                line
            )

            pdf.set_font(
                "Times",
                "",
                11
            )

        # Uppercase heading
        elif line.upper() == line and len(line) < 100:

            if pdf.get_y() > pdf.h - 30:
                pdf.add_page()

            pdf.set_font(
                "Times",
                "B",
                11
            )

            _pdf_write_wrapped(
                pdf,
                line
            )

            pdf.set_font(
                "Times",
                "",
                11
            )

        # Normal paragraph
        else:

            _pdf_write_wrapped(
                pdf,
                line
            )

        pdf.ln(1)

    output = pdf.output()

    if isinstance(output, str):
        return output.encode("latin-1")

    return bytes(output)